### ISSUE TITLE
访问路由配置目录，dashboard面板会报错

### ISSUE THREAD

**Issue by gzldx** [tech-microworld/ws-cloud-gateway#22]
<img width="1123" alt="WX20200704-114756@2x" src="https://user-images.githubusercontent.com/2508193/86504563-47a2bb00-bdec-11ea-8202-30df73bfa630.png">

排查到的原因是etcdv3不再支持目录，读取目录返回body为空

2020/07/04 11:47:46 [error] 77413#769791: *12 lua entry thread aborted: runtime error: ws-cloud-gateway/gateway/app/store/route_store.lua:57: attempt to index field 'body' (a nil value)
stack traceback:
coroutine 0:
	.../ws-cloud-gateway/gateway/app/store/route_store.lua: in function 'query_list'
	.../ws-cloud-gateway/gateway/admin/routes.lua:25: in function 'fun'
	.../ws-cloud-gateway/gateway/admin/init.lua:128: in function 'handler'
	.../ws-cloud-gateway/deps/share/lua/5.1/resty/radixtree.lua:627: in function 'dispatch'
	.../ws-cloud-gateway/gateway/admin/init.lua:163: in function 'http_admin'
	content_by_lua(gateway.conf:28):3: in main chunk, client: 127.0.0.1, server: _, request: "GET /admin/routes/list HTTP/1.1", host: "localhost:10000", referrer: "http://localhost:10000/dashboard"

**Comment by fengjx** [comment]
`curl http://127.0.0.1:2379/version` 看下你的 etcd 版本是多少，3.4.x 才支持（3.5 还没发布），其他版本是测试版，请求url不同
![image](https://user-images.githubusercontent.com/4881720/86507008-416e0800-be07-11ea-8c93-80ec9a597046.png)
参考 etcd 文档：<https://etcd.io/docs/v3.4.0/dev-guide/api_grpc_gateway/>

**Comment by gzldx** [comment]
我的版本是3.3.22，把api_prefix = "/v3"就没报错了

**Comment by gzldx** [comment]
3.3.22还不支持grpc吗？我已经在conf.yml加上enable-grpc-gateway:true

**Comment by fengjx** [comment]
都支持的，只是默认 api_prefix 不相同
