### ISSUE TITLE
您好 现在项目还在维护吗，这种插件的实现机制，当不同的插件操作ngx.ctx,ngx.var的变量时，会不会造成插件之间相互影响？

### ISSUE THREAD

**Issue by ysc972** [tech-microworld/ws-cloud-gateway#34]
您好 现在项目还在维护吗，这种插件的实现机制，当不同的插件操作ngx.ctx,ngx.var的变量时，会不会造成插件之间相互影响？

**Comment by fengjx** [comment]
对全局对象是会相互影响的，如果不想影响，可以自己定义一个自己的变量来传递，这个可以自己实现，但项目本身没有限制

ps: 还在维护，就是之前太忙了没更新，后面会继续维护
