### ISSUE TITLE
更新路由会把路由删除

### ISSUE THREAD

**Issue by ss1917** [tech-microworld/ws-cloud-gateway#42]
-- 如果路由前缀修改了，需要删除之前的路由配置
    if err == nil and key and key ~= route.prefix then
        _, err = remove_route(key)
    end
路由修改后都被删除了，应该为这样

    if err == nil and key and key ~= create_key(route.prefix) then
        _, err = remove_route(key)
    end

**Comment by fengjx** [comment]
已解决
